
server:
 port: 1122
#  port: 1124
    
jwt:
    secret: secretkey
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
       default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
       globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
       routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**  
          filters: 
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown
        - id: web-sockets
          uri: lb://WEB-SOCKETS
          predicates:
            - Path=/websockets/**        
          filters:
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown         
                
        - id: vms-service
          uri: lb://VMS-SERVICE
          predicates:
            - Path=/vms/**        
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown
               
            
        - id:  dashboard-service
          uri: lb://DASHBOARD-SERVICE
          predicates:
            - Path=/dashboard/**        
          filters:
            - AuthenticationFilter 
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown
            
        - id:  taskmanagement-service
          uri: lb://TASKMANAGEMENT-SERVICE
          predicates:
            - Path=/task/**        
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown
                
                
        - id:  consultant-servicce
          uri: lb://CONSULTANT-SERVICE
          predicates:
             - Path=/consultant/**        
          filters:
             - AuthenticationFilter    
             
             
        - id:  immigration-service
          uri: lb://IMMIGRATION-SERVICE
          predicates:
             - Path=/img/**        
          filters:
             - AuthenticationFilter 
             - name: CircuitBreaker
               args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown   
             
        - id:  requirements-service
          uri: lb://REQUIREMENT-SERVICE
          predicates:
             - Path=/requirement/**        
          filters:
             - AuthenticationFilter    
             - name: CircuitBreaker
               args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown  
                
        - id:  submission-service
          uri: lb://SUBMISSIONS-SERVICE
          predicates:
             - Path=/submission/**        
          filters:
             - AuthenticationFilter    
             - name: CircuitBreaker
               args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown  
                
        - id:  interview-service
          uri: lb://INTERVIEW-SERVICE
          predicates:
             - Path=/interview/**        
          filters:
             - AuthenticationFilter    
             - name: CircuitBreaker
               args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown
                
        - id:  kpt-service
          uri: lb://KPT-SERVICE
          predicates:
             - Path=/kpt/**        
          filters:
             - AuthenticationFilter    
             - name: CircuitBreaker
               args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown

        - id:  billpay-service
          uri: lb://BILLPAY-SERVICE
          predicates:
             - Path=/billpay/**        
          filters:
             - AuthenticationFilter    
             - name: CircuitBreaker
               args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown
                
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/mail/**        
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown 
        - id: openreqs-service
          uri: lb://OPENREQS-SERVICE
          predicates:
            - Path=/openreqs/**        
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown    
        - id: reports-service
          uri: lb://REPORTS-SERVICE
          predicates:
            - Path=/report/**        
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown 
                
                
        - id: dropbox-service
          uri: lb://DropBox-SERVICE
          predicates:
            - Path=/dropbox/**        
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ServerDown
                fallbackUri: forward:/fallback/serviceDown
                
               
        
 
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
      
      
management:
  endpoints:
    web:
      exposure:
        include: health,gateway,info,env
        
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 3
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
