version: 0.0
os: linux
files:
  - source: /target/eureka-server.jar
    destination: /home/ec2-user/eureka-server.jar
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
